
name: Test Project

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
      with:
        python-version: '3.12'

      - name: Check test file
        run: test -f test.txt

      - name: Check file content
        run: grep "Devops Git project" test.txt

      - name: Build project
        run: echo "Building project..."

      - name: Show file
        run: cat test.txt
